import eslint from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import eslintPluginImport from 'eslint-plugin-import';
import reactHooks from 'eslint-plugin-react-hooks';
// eslint-disable-next-line import/namespace -- the plugin ships modern syntax import/namespace can't parse
import { reactRefresh } from 'eslint-plugin-react-refresh';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import tseslint from 'typescript-eslint';

export default defineConfig([
  globalIgnores([
    '**/dist',
    '**/coverage',
    '**/playwright-report/',
    '**/test-results/',
    '.turbo',
    'apps/mobile/', // Capacitor native projects + generated bridge code
    'supabase/functions/', // Deno runtime — https/npm: imports, not part of the Node TS projects
    'scripts/', // one-off ops scripts, mostly Deno
    'packages/db/src/database.types.ts', // generated by `supabase gen types`
    'sourdough/', // colleague's repo, vendored for reference only
    'ToC/',
    'test-images/',
  ]),
  {
    files: ['**/*.{js,mjs,cjs,ts,tsx}'],
    extends: [
      eslint.configs.recommended,
      eslintPluginImport.flatConfigs.recommended,
      eslintPluginImport.flatConfigs.typescript,
    ],
    settings: {
      'import/resolver': { typescript: true },
    },
    plugins: {
      'simple-import-sort': simpleImportSort,
    },
    rules: {
      eqeqeq: ['error', 'always', { null: 'ignore' }], // `== null` is our nullish-check idiom
      'import/no-amd': 'error',
      'import/no-empty-named-blocks': 'error',
      'import/no-extraneous-dependencies': [
        'error',
        {
          // devDependencies can be imported in config, test, and e2e files
          devDependencies: [
            '**/*.config.{js,mjs,ts}',
            '**/*.{spec,test}.{ts,tsx}',
            '**/tests/**/*.{ts,tsx}',
            'apps/web/e2e/**',
            'eslint.config.mjs',
          ],
          includeInternal: true,
        },
      ],
      'import/no-import-module-exports': 'error',
      'import/no-named-as-default': 'error',
      'import/no-named-as-default-member': 'off', // produces false positives
      'no-console': 'warn',
      // Playwright fixtures destructure `({}, use)` by design.
      'no-empty-pattern': ['error', { allowObjectPatternsAsParameters: true }],
      'no-param-reassign': 'error',
      'no-throw-literal': 'error',
      'no-unused-vars': ['error', { args: 'none', caughtErrors: 'none' }],
      'simple-import-sort/imports': 'warn',
    },
  },
  {
    // CJS config files consumed by tools that don't read ESM (postcss, tailwind)
    files: ['**/*.{js,cjs}'],
    languageOptions: { globals: { module: 'writable', require: 'readonly' } },
    rules: { 'no-undef': 'off' },
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: { parserOptions: { projectService: true } },
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { args: 'none', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
      '@typescript-eslint/no-misused-promises': [
        'error',
        {
          // these exceptions reduce unnecessary friction with React stuff
          checksVoidReturn: {
            arguments: false,
            attributes: false,
          },
        },
      ],
      '@typescript-eslint/restrict-template-expressions': 'off', // always allow `${x}` regardless of x's type
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'error', // complements strict mode for chained promises
      // Staged at `warn` for the initial adoption — large existing backlogs
      // (~150 each). Promote to `error` once the cleanup pass lands.
      '@typescript-eslint/no-unnecessary-condition': 'warn',
      '@typescript-eslint/no-floating-promises': 'warn',
    },
  },
  {
    // Tooling configs live outside the per-package tsconfig projects;
    // lint them without type information.
    files: ['**/*.config.{ts,mts}'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    files: ['apps/web/src/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended, reactRefresh.configs.recommended],
    rules: {
      // React-Compiler-era rules with existing backlogs; staged at `warn`
      // like the typed rules above. rules-of-hooks + exhaustive-deps stay
      // at their recommended (error) severity.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/purity': 'warn',
      'react-hooks/refs': 'warn',
      'react-hooks/preserve-manual-memoization': 'warn',
    },
  },
  {
    // Test files may need `any` and partial mocks in ways we prevent in
    // normal code.
    files: ['**/*.{spec,test}.{ts,tsx}', '**/tests/**', 'apps/web/e2e/**'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/unbound-method': 'off',
      // Test shims implement Promise-returning contracts without awaiting.
      '@typescript-eslint/require-await': 'off',
      'no-console': 'off',
    },
  },
]);
