-- Recipe cover images: storage-path column on recipes.
--
-- A recipe can carry one cover image — uploaded by the user (same `covers`
-- public bucket + path convention as collection covers, 20260419000200) or
-- generated by the Gemini cover worker (20260626000100). The column holds the
-- storage *path* (`{owner_id}/recipes/{recipe_id}.{ext}`); the public URL is
-- derived client-side via storage.getPublicUrl. It rides along on the recipe
-- row through the existing sync push (save_recipes_graph) / pull (select *) and
-- — because recipes already carry denormalized owner_id/household_id with a
-- claim-based read policy — is visible to household co-members with no extra
-- RLS work.

alter table public.recipes add column if not exists cover_image_path text;

-- save_recipes_graph (20260615000000) upserts the recipe row from a jsonb
-- payload via jsonb_populate_recordset, which picks up the new column
-- automatically; we only need to add it to the ON CONFLICT update set so an
-- edit-then-push preserves / updates the cover path. Otherwise byte-identical
-- to 20260615000000.
create or replace function public.save_recipes_graph(p_recipes jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_recipes jsonb;   -- deduped: one item per recipe id (last wins)
  v_ids uuid[];
begin
  if p_recipes is null or jsonb_typeof(p_recipes) <> 'array' then
    raise exception 'save_recipes_graph: p_recipes must be a jsonb array';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_recipes) item
    where jsonb_typeof(item -> 'recipe') <> 'object' or (item -> 'recipe' ->> 'id') is null
  ) then
    raise exception 'save_recipes_graph: every item needs a recipe object with an id';
  end if;

  select jsonb_agg(item order by ord)
    into v_recipes
  from (
    select distinct on ((item -> 'recipe' ->> 'id')) item, ord
    from jsonb_array_elements(p_recipes) with ordinality as t(item, ord)
    order by (item -> 'recipe' ->> 'id'), ord desc
  ) d;

  if v_recipes is null then
    return;
  end if;

  select array_agg((item -> 'recipe' ->> 'id')::uuid)
    into v_ids
  from jsonb_array_elements(v_recipes) item;

  insert into public.recipes
  select * from jsonb_populate_recordset(
    null::public.recipes,
    (select jsonb_agg(
        ((item -> 'recipe') - 'created_at' - 'updated_at')
        || jsonb_build_object('created_at', now(), 'updated_at', now()))
       from jsonb_array_elements(v_recipes) item))
  on conflict (id) do update set
    collection_id       = excluded.collection_id,
    title               = excluded.title,
    servings_amount     = excluded.servings_amount,
    servings_description = excluded.servings_description,
    sort_order          = excluded.sort_order,
    notes               = excluded.notes,
    parent_recipe_id    = excluded.parent_recipe_id,
    description         = excluded.description,
    time_estimate       = excluded.time_estimate,
    equipment           = excluded.equipment,
    book_title          = excluded.book_title,
    page_numbers        = excluded.page_numbers,
    source_image_text   = excluded.source_image_text,
    servings_amount_max = excluded.servings_amount_max,
    starred             = excluded.starred,
    source_url          = excluded.source_url,
    cover_image_path    = excluded.cover_image_path;

  delete from public.ingredients where recipe_id = any (v_ids);
  delete from public.instructions where recipe_id = any (v_ids);

  insert into public.ingredients
  select * from jsonb_populate_recordset(null::public.ingredients,
    (select coalesce(jsonb_agg(ing), '[]'::jsonb)
       from jsonb_array_elements(v_recipes) item,
            jsonb_array_elements(coalesce(item -> 'ingredients', '[]'::jsonb)) ing));

  insert into public.instructions
  select * from jsonb_populate_recordset(null::public.instructions,
    (select coalesce(jsonb_agg(s), '[]'::jsonb)
       from jsonb_array_elements(v_recipes) item,
            jsonb_array_elements(coalesce(item -> 'instructions', '[]'::jsonb)) s));

  insert into public.instruction_ingredient_refs
  select * from jsonb_populate_recordset(null::public.instruction_ingredient_refs,
    (select coalesce(jsonb_agg(rf), '[]'::jsonb)
       from jsonb_array_elements(v_recipes) item,
            jsonb_array_elements(coalesce(item -> 'refs', '[]'::jsonb)) rf));
end;
$$;

revoke all on function public.save_recipes_graph(jsonb) from public;
grant execute on function public.save_recipes_graph(jsonb) to authenticated;
